[global]
disableWatchdogWarning = false
disableWidgetStateDuplicationWarning = false

[client]
showErrorDetails = false
caching = true
displayEnabled = true
toolbarMode = "auto"

[server]
headless = true

[runner]
fastReruns = true

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"